payment-config.supportedAccounts: BARCELONA,TENERIFE,CRETE,LONDON,PARIS

management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: metrics,info,health,prometheus

harness:
  se: ${HARNESS_SE:nik}
  build: ${HARNESS_BUILD:1}
  clientFF: ${HARNESS_CLIENT_FF:sdkkey}
  api:
    key: ${HARNESS_FF_KEY:1260ecd9-0af2-43d0-98f6-06570bb13a00}
