payment-config.supportedAccounts: BARCELONA,TENERIFE,CRETE,LONDON,PARIS

management.endpoints.web.base-path: "/"
management.endpoints.web.exposure.include: "*"
management.health.defaults.enabled: true

management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.metrics.enabled=true
management.endpoint.prometheus.enabled=true
management.endpoint.health.show-details=always
management.endpoint.health.show-components=always
management.endpoint.health.probes.enabled=true
management.metrics.tags.application=TheApplicationName

harness:
  se: ${HARNESS_SE:nik}
  build: ${HARNESS_BUILD:1}
  clientFF: ${HARNESS_CLIENT_FF:sdkkey}
  api:
    key: ${HARNESS_FF_KEY:1260ecd9-0af2-43d0-98f6-06570bb13a00}
