payment-config.supportedAccounts: BARCELONA,TENERIFE,CRETE,LONDON,PARIS

management.endpoints.web.base-path: "/"
management.health.defaults.enabled: true

harness:
  se: ${HARNESS_SE:nik}
  build: ${HARNESS_BUILD:1}
  clientFF: ${HARNESS_CLIENT_FF:sdkkey}
  api:
    key: ${HARNESS_FF_KEY:1260ecd9-0af2-43d0-98f6-06570bb13a00}
