apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
 name: ingress-router-{{ lower .Values.sename }}
 annotations:
   kubernetes.io/ingress.class: nginx
   nginx.ingress.kubernetes.io/snippets-enabled: "true"
   nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - host: {{ lower .Values.sename }}.citibanamex.harness-demo.site
    http:
     paths:
     - pathType: ImplementationSpecific
       backend:
          service:
             name: payment-service-{{lower .Values.sename }}-svc
             port:
               number: 8080
