apiVersion: v1
kind: Service
metadata:
  name: {{lower .Values.name}}-{{ lower .Values.sename}}-svc
  labels:
    job: {{lower .Values.name}}-{{ lower .Values.sename}}
    app: service-{{lower .Values.name}}-{{ lower .Values.sename}}
spec:
  type: {{.Values.serviceType}}
  ports:
  - port: {{.Values.servicePort}}
    targetPort: {{.Values.serviceTargetPort}}
    protocol: TCP
    name: web
  selector:
    app: {{lower .Values.name}}-{{lower .Values.sename}}
