apiVersion: v1
kind: Service
metadata:
{{- if lower .Values.sename}}
  name: {{lower .Values.name}}-{{ lower .Values.sename}}-svc
{{- else }}
  name: {{ lower .Values.name}}-svc
{{- end }}
  labels:
    job: {{lower .Values.name}}-{{lower .Values.sename}}
    app: {{lower .Values.name}}-{{ lower .Values.sename}}-svc
spec:
  type: {{.Values.serviceType}}
  ports:
  - port: {{.Values.servicePort}}
    targetPort: {{.Values.serviceTargetPort}}
    protocol: TCP
    name: web
  selector:
  {{- if lower .Values.sename }}
    app: {{lower .Values.name}}-{{lower .Values.sename}}
  {{- else }}
    app: {{lower .Values.name}}
 {{- end }}
