apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: Trigger-Github-Action
  title: Trigger Github Action
  description: execute github action
  tags:
    - github
spec:
  owner: cristian.ramirez@harness.io
  type: service
  parameters:
    type: object
    properties:
      idpUrl:
        type: string
        title: URL del Proveedor de Identidad
  
  steps:
    - id: excecut-github-action
      name: Execute Github Action
      action: http:backstage:request
      input:
        method: 'POST'
        path: '{{ parameters.idpUrl }}' # URL del IdP proporcionada por el usuario.
        headers:
          Accept: 'application/vnd.github.v3+json'
          Authorization: '{{ secrets.cristian_github_token }}'
        body:
          event_type: 'run-action'


