name: Compilar Aplicación Java con Maven

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Comprobar el código
        uses: actions/checkout@v2

        
      - name: Run commands in Docker container
        run: |
          docker run --rm -v ${{ github.workspace }}:/workspace -w /workspace nikpap/mvn-openjdk-8:harness /bin/bash -c "
            cd payment-service
            mvn -Dmaven.test.skip=true clean install -X
            ls -la
          "
