name: Compilar Aplicación Java con Maven

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Comprobar el código
        uses: actions/checkout@v2

      - name: Configurar JDK
        uses: actions/setup-java@v2
        with:
          java-version: '8' # Especifica que deseas usar OpenJDK 8
          distribution: 'adopt' # Puedes cambiar a 'zulu' si prefieres esa distribución

      - name: Compilar con Maven
        run: mvn clean install
        working-directory: payment-service
