name: Compilar Aplicación Java con Maven

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Comprobar el código
        uses: actions/checkout@v2

      - name: Ejecutar Maven dentro del contenedor
        run: |
          docker run --rm nikpap/mvn-openjdk-8:harness mvn clean install
        working-directory: payment-service
        
