name: Ejecutar Acción mediante HTTP

on:
  repository_dispatch:
    types: [run-action] # Define un tipo de evento personalizado

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Comprobar el código
        uses: actions/checkout@v2

      - name: Ejecutar tarea
        run: echo "Acción ejecutada a través de HTTP"
